"""Alle vaste getallen van het spel bij elkaar."""

VENSTER_BREEDTE = 900
VENSTER_HOOGTE = 700
VENSTER_TITEL = "Boeven Redden!"

SPELER_SNELHEID = 4
SPELER_BREEDTE = 28
SPELER_HOOGTE = 44
MAX_LEVENS = 5

POLITIE_BREEDTE = 26
POLITIE_HOOGTE = 40
POLITIE_START_SNELHEID = 2.0
POLITIE_MAX_SNELHEID = 5.5
POLITIE_START_INTERVAL = 12.0
POLITIE_MIN_INTERVAL = 3.0

BOEF_STRAAL = 14
AANTAL_BOEFEN = 8

HUIS_X = 100
HUIS_Y = 100
HUIS_BREEDTE = 80
HUIS_HOOGTE = 80

STATUS_SPELEN = "spelen"
STATUS_GAME_OVER = "game_over"

SCHADE_PAUZE = 1.5

BOVENBALK_HOOGTE = 36
LEVENSBALK_BREEDTE = 160
LEVENSBALK_HOOGTE = 16
